INSERT INTO `codebarcakephp`.`brands` (`name`, `link_to_warranty_check`) VALUES ('Dell', 'www.dell.ch/support');
INSERT INTO `codebarcakephp`.`brands` (`name`, `link_to_warranty_check`) VALUES ('Lenovo', 'www.lenovo.com/checkwarranty');
INSERT INTO `codebarcakephp`.`brands` (`name`, `link_to_warranty_check`) VALUES ('Apple', 'www.apple.ch/support');
INSERT INTO `codebarcakephp`.`brands` (`name`, `link_to_warranty_check`) VALUES ('HP', 'www.hp.ch');

INSERT INTO `codebarcakephp`.`device_categories` (`name`) VALUES ('laptop');
INSERT INTO `codebarcakephp`.`device_categories` (`name`) VALUES ('batterie');
INSERT INTO `codebarcakephp`.`device_categories` (`name`) VALUES ('hdd');
INSERT INTO `codebarcakephp`.`device_categories` (`name`) VALUES ('sdd');
INSERT INTO `codebarcakephp`.`device_categories` (`name`) VALUES ('chargeur');
INSERT INTO `codebarcakephp`.`device_categories` (`name`) VALUES ('graveur DVD');

UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='1';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='2';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='3';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='4';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='5';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='6';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='7';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='8';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='9';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='10';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='11';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='12';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='13';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='14';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='15';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='16';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='17';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='18';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='19';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='20';
UPDATE `codebarcakephp`.`device_types` SET `device_category_id`=1 WHERE `id`='21';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='22';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='29';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='23';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='24';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='25';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='26';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='27';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='28';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='30';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='31';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='32';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='33';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='34';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='35';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='36';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='37';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='38';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='39';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='40';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='41';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='42';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='43';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='44';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='45';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='46';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='47';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='48';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='49';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='50';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='51';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='52';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=1, `device_category_id`=1 WHERE `id`='53';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='54';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='55';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='56';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='57';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='58';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='59';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='60';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='61';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='62';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='63';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='64';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='65';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='66';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='67';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='68';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=3, `device_category_id`=1 WHERE `id`='69';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='70';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='71';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='72';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='73';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=2, `device_category_id`=1 WHERE `id`='74';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='75';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='76';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='77';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='78';
UPDATE `codebarcakephp`.`device_types` SET `brand_id`=4, `device_category_id`=1 WHERE `id`='79';

INSERT INTO `codebarcakephp`.`languages` (`name`) VALUES ('Français');
INSERT INTO `codebarcakephp`.`languages` (`name`) VALUES ('Anglais');
INSERT INTO `codebarcakephp`.`languages` (`name`) VALUES ('Allemand');
INSERT INTO `codebarcakephp`.`languages` (`name`) VALUES ('Italien');